#!/usr/bin/env python3
"""Shared JCR impact-factor / quartile lookup.

Source of truth: scripts/data/jcr_2025.json — a slim export of the Clarivate
JCR table (2025 JIF), regenerated by scripts/build_jcr_data.py when a new
table is released. Both fetch_publications.py (per-paper, ISSN + name) and
refresh_impact_factors.py (bulk, name only) use this module so there is one
matching implementation and one data source.

No third-party dependency at lookup time (stdlib json only).
"""
import json
import re
from pathlib import Path

DATA = Path(__file__).resolve().parent / "data" / "jcr_2025.json"

# Bridges for journals whose PubMed name doesn't normalize to the Clarivate
# (acronym-style) title. Keyed norm(bib journal) -> norm(Clarivate name).
ALIASES = {
    "BMJ": "BMJ BRITISH MEDICAL JOURNAL",
    "QJM": "QJM AN INTERNATIONAL JOURNAL OF MEDICINE",
    "PSORIASIS": "PSORIASIS TARGETS AND THERAPY",
}


def clean_journal(s):
    """Reduce a PubMed-style journal name toward the Clarivate form:
    drop parentheticals, cut at ' : <abbrev>' / ' = <alt name>', strip leading 'The'."""
    if not s:
        return ""
    s = re.sub(r"\(.*?\)", " ", str(s))
    s = re.split(r"\s[:=]\s", s)[0]
    s = re.sub(r"^\s*the\s+", "", s, flags=re.I)
    return s


def norm(s):
    if not s:
        return ""
    s = clean_journal(s).upper()
    s = re.sub(r"[.,&\-:/]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def best_quartile(json_str, col_q):
    """Best (Q1 < Q2 < ...) JIF quartile across a journal's categories.
    Used by build_jcr_data.py when generating the slim data file."""
    qs = []
    try:
        for c in json.loads(json_str or "[]"):
            q = c.get("quartile")
            if q and re.match(r"^Q[1-4]$", str(q)):
                qs.append(str(q))
    except Exception:
        pass
    if col_q and re.match(r"^Q[1-4]$", str(col_q)):
        qs.append(str(col_q))
    return min(qs) if qs else None


_INDEX = None


def _load():
    global _INDEX
    if _INDEX is None:
        idx = {}
        data = json.loads(DATA.read_text(encoding="utf-8"))
        for r in data["journals"]:
            rec = {"impact_factor": f"{r['f']:.1f}", "jcr_quartile": r["q"]}
            # raw ISSNs (keep hyphen) + normalized names/abbrev
            for k in ((r.get("i") or "").strip(), (r.get("e") or "").strip(),
                      norm(r.get("n")), norm(r.get("a"))):
                if k:
                    idx.setdefault(k, rec)
        _INDEX = idx
    return _INDEX


def lookup(issn=None, eissn=None, name=None, abbrev=None):
    """Return {"impact_factor": "45.1", "jcr_quartile": "Q1"} or {}.
    Tries ISSN/eISSN (exact), then normalized name/abbrev, then ALIASES."""
    idx = _load()
    for raw in (issn, eissn):
        if raw and str(raw).strip() in idx:
            return dict(idx[str(raw).strip()])
    for nm in (name, abbrev):
        k = norm(nm)
        if not k:
            continue
        if k in idx:
            return dict(idx[k])
        if k in ALIASES and ALIASES[k] in idx:
            return dict(idx[ALIASES[k]])
    return {}
